import './globals.css'
import {Inter} from 'next/font/google'
import _AppBar from "@/app/components/_AppBar";
import Provider from "@/app/providers/Provider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Provider>
            <_AppBar/>
            {children}
        </Provider>
        </body>
        </html>
    )
}
